### ISSUE TITLE
这里似乎应该是page: darkPageBg，而不是pageBg: darkPageBg？

### ISSUE THREAD

**Issue by zhaoyunyes** [ModyQyW/tailwind-extensions#20]
https://github.com/ModyQyW/tailwind-extensions/blob/bbff9910ec9977776abbc87796a8692402f33c97/src/presets/element-plus.ts#L264

**Comment by ModyQyW** [comment]
非常感谢指出这个问题！我已经发布了 0.22.1 修复了这个问题，请试试。
